name: 'ðŸž Bug report'
description: Report an issue.
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have confirmed this bug exists on the
            [latest version](https://github.com/pola-rs/polars-cli/releases/latest) of the Polars CLI.
          required: true

  - type: textarea
    id: example
    attributes:
      label: Reproducible example
      description: >
        Copy and paste the command(s) you ran and any relevant log output.
      placeholder: polars -c "SELECT * from read_csv('data.csv')"
      render: shell
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Issue description
      description: >
        Provide any additional information you think might be relevant.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: >
        Describe or show an example of the expected behavior.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Installed version
      placeholder: '0.3.0'
    validations:
      required: true
