# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
- name: '❓ Question'
  url: https://stackoverflow.com/questions/ask?tags=polars-cli
  about: |
    Ask a question about the Polars CLI on Stack Overflow.
- name: '💬 Discord server'
  url: https://discord.gg/4UfP5cfBE7
  about: |
    Chat with the community and Polars maintainers about the usage and development of the project.
